apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: gangadhariy/my-java-app:latest
        ports:
        - containerPort: 8080# Updated at Mon Sep 23 10:16:55 UTC 2024
# Updated at Mon Sep 23 10:40:57 UTC 2024
# Updated at Mon Sep 23 10:44:31 UTC 2024
