name: Java Maven Build and Docker1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: arc-runner-set

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 2375:2375

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
      # Step 2: Set up JDK (Java 11)
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      # Step 3: Build with Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build the Docker image
      - name: Build Docker image
        run: |
         docker build -t ${{ secrets.DOCKER_USERNAME }}/my-java-app:latest .

      # Step 6: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-java-app:latest
#      - name: Build and push Docker image with Kaniko
#        uses: gcr.io/kaniko-project/executor@v1.6.0
#        with:
#         args: --dockerfile=Dockerfile --context=. --destination=${{ secrets.DOCKER_USERNAME }}/my-java-app:latest

      - name: Clone argocd repo
        run: |
          mkdir ../argocd-repo
          git clone https://github.com/gangadhariy/argocd.git ../argocd-repo
          cd ../argocd-repo
          git checkout master


      - name: Update Kubernetes Deployment
        run: |
          sed -i "s|image: gangadhariy/my-java-app:.*|image: ${{ secrets.DOCKER_USERNAME }}/my-java-app:latest|" manifests/deployment.yaml
          echo "# Updated at $(date)" >> manifests/deployment.yaml
      - name: Configure Git
        run: |
          git config --global user.name "gangadhariy"
          git config --global user.email "gangadharyaleholi12@gmail.com"
          
          
     
      
      # Step 9: Commit Changes
      - name: Commit Changes
        run: |
          git add .
          git commit -m "Update deployment image tag to latest"

      # Step 10: Push Changes
      - name: Push Changes
        run: |
           git push https://${{ secrets.PAT_TOKEN }}@github.com/gangadhariy/argocd.git master
